### PR TITLE
Add NuxtJS support

### PR DESCRIPTION
**Pull request by jonbeckman**
Added NuxtJS support. The biggest difference from the Next impl is the use of Nuxt's server api routes to handle Polar SDK. In Nuxt, this is how we keep PATs server-side and hidden from the user. 

This impl makes some assumptions, based on what I deem a typical Nuxt project:
- Directory structure (users can manually move the files to their repo's correct locations, if needed)
- Magic imports (users can manually import dependencies, if needed)
- `useRuntimeConfig` for secret handling

>I used GitHub Copilot Workspace for the initial migration, then hand crafted the rest.

### CODE REVIEW

**Comment by unibeck** [comment]
Ran `npx polar-init` on [this Nuxt Starter template](https://github.com/nuxt-hub/starter) as a test and it worked perfectly. Here are the changes to expect.
image

@emilwidlund would you be able to test this branch against a NextJS project to make sure there are no regressions?

**Comment by emilwidlund** [comment]
@unibeck Amazing! Very much appreciated! Will take a look at this today.

**Comment by emilwidlund** [comment]
@unibeck Looks really good! I'm however encountering an issue when running the nuxt-starter.

image

Looks like something is a little off with that `usePolar` import?

**Comment by emilwidlund** [comment]
Also, it would be nice if we somehow could pre-populate the polarOrgId in the runtimeConfig automatically.

**Comment by unibeck** [comment]
Ah this is how `~/` is interpreted. On my project, `~/` is the repo's root dir,  whereas the default of `~/` is `./app/`. Sorry about that, let me move the `./utils` dir into the `./app` dir.

Let me look into the pre-populating `polarOrgId` as well, nice suggestion.

**Comment by unibeck** [comment]
I fixed the polar util issue.

As for pre-populating the values in runtimeConfig, I did add the `NUXT_` prefix which helps Nuxt default import those env vars. Though there are two more steps the user has to manually take to get those env vars.
1. run Nuxt with `--dotenv .env.local`
2. manually add the `polarServer`, `polarAccessToken`, `polarOrganizationId`, `polarWebhookSecret` keys to runtimeConfig in the `nuxt.config.(ts/mjs/js)` file. See [Nuxt's docs](https://nuxt.com/docs/guide/going-further/runtime-config#environment-variables)
>Your desired variables must be defined in your nuxt.config. This ensures that arbitrary environment variables are not exposed to your application code.

I tried automating this, though it gets convoluted very quickly. We would need to support each `nuxt.config` file types, then parse it to find defineNuxtConfig and the runtimeConfig objects. Instead, is there a place in the docs/cli where we can tell users of these two extra manually steps?

**Comment by emilwidlund** [comment]
@unibeck Nice work! I'm going to merge this. I'll add a few tweaks in regards to notifying about manually adding the runtimeConfig, etc. 

I'll issue a new release to NPM once I have that in place. 

Thanks again! Really nice to see this evolve & to support multiple types of frameworks going forward :)

**Comment by unibeck** [comment]
Thanks Emil! I'll keep an eye out for the release to share with the Nuxt community and on X.

**Pull request merged**
